language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'versioninfo(); Pkg.clone(pwd()); Pkg.build("Scalar"); Pkg.test("Scalar"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Scalar")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
